[package]
name = "mips_sim"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "^0.4.0"
num_enum = "0.5.4"
paste = "^1.0"
lazy_static = "^1.4.0"

[dev-dependencies]
paste = "^1.0"
