.text
lui		$t0, 0x8000
addiu	$t1, $zero, 1

srlv	$t2, $t1, $t0
addiu	$t1, $t1, 1

srlv	$t3, $t1, $t0 
addiu	$t1, $t1, 1

srlv	$t4, $t1, $t0
addiu	$t1, $t1, 1

srlv	$t5, $t1, $t0
addiu	$t1, $t1, 1

srlv	$t6, $t1, $t0
addiu	$t1, $t1, 1

srlv	$t7, $t1, $t0
addiu	$t1, $t1, 1

srlv	$t8, $t1, $t0
addiu	$t1, $t1, 1

srlv	$v0, $t1, $t0
addiu	$t1, $t1, 1

srlv	$v1, $t1, $t0
addiu	$t1, $t1, 1

srlv	$a0, $t1, $t0
addiu	$t1, $t1, 1

srlv	$a1, $t1, $t0
addiu	$t1, $t1, 1

srlv	$a2, $t1, $t0
addiu	$t1, $t1, 1

srlv	$a3, $t1, $t0
